.TH "8SVXPACK" "1" "January 2012" "8svxpack 0.1" "Command Reference"
.SH "NAME"
8svxpack \- Compress or decompress 8SVX instruments inside an IFF file
.SH "SYNOPSIS"
\fB8svxpack\fR [\fIoptions\fR] [\fIfile.8SVX\fR]
.SH "DESCRIPTION"
.PP
The command \fB8svxpack\fR compresses or decompresses all the BODY chunks of all
8SVX forms in the given IFF file using the fibonacci delta algorithm. If no
IFF file is specified, it reads an IFF file from the standard input.
.SH "OPTIONS"
\fB\-c\fR, \fB\-\-compress\fR
.RS 4
Compresses all BODY chunks of 8SVX forms
.RE
.PP
\fB\-d\fR, \fB\-\-decompress\fR
.RS 4
Decompresses all BODY chunks of 8SVX forms
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Shows the usage of this command to the user
.RE
.PP
.SH "AUTHOR"
.PP
\fBSander van der Burg\fR
.br
.RS 4
Author
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 Sander van der Burg
.br
